- README.md
Updating with the credential file to be used with LOFAR_stager.py
> Update README.md for LOFAR_stager.py

- container/Dockerfile
Later it still crashes when cloning DDFacet, but I do not know if there is a correct commit at https://github.com/saopicc/DDFacet.git.
> Fix Docker build

- README.md
There was a typo that prevented it from running.
BTW fix link to LOFAR.
> Fix PILL patch

- container/Dockerfile
Comment out DDF (https://github.com/revoltek/LiLF/pull/42#issuecomment-2642429110). Build will work after that.
> Comment out DDF

- LiLF/lib_ddfacet.py
- LiLF/lib_img.py
- LiLF/lib_multiproc.py
- LiLF/lib_util.py
- LiLF/make_mask.py
This also appears to never be accessed.
> Remove more unused imports

- README.md
The same as https://github.com/revoltek/LiLF/pull/44 but to `LBAdevel` branch.
> Fix Pill.py and LOFAR link

- pipelines/LOFAR_preprocess.py
- pipelines/LOFAR_quality.py
- pipelines/LOFAR_timesplit.py
- pipelines/PiLL-survey.py
- pipelines/PiLL.py
There is more, but I think it would be difficult to review a PR if I put it all in one PR.
> Remove more unused modules #2

- pipelines/LOFAR_cal.py
- pipelines/LOFAR_ddparallel.py
- scripts/addcol2ms.py
- scripts/breizorro.py
- scripts/ds9_facet_generator.py
> Remove unused imports 4

- scripts/LOFAR_dbobs.py
- scripts/LOFAR_stager.py
- scripts/make_aterm_images.py
- scripts/make_gain_screen.py
- scripts/reweight.py
> Remove unused modules 5

- container/Dockerfile-20250113
Makes it clone 91 instead of 258 MB.
> Slight speedup in container building

- scripts/eval_ampres.py
- scripts/flagonmindata.py
- scripts/h5_merger.py
This is the last one, I see nothing more. At this point the pipeline crashes for me (https://github.com/revoltek/LiLF/issues/59), but for unrelated reasons.
> Remove unused modules 6

- README.md
Fix trailing spaces, new line file ending and `Command line parameters` header.
> Minor fixes for `README.md`

- scripts/ds9_facet_generator.py
> Comment unused variable

- container/Dockerfile-20250113
Hopefully it will compute a bit faster. GCC 14 has improved vectorization, for example.
I had to update EveryBeam, WSClean and DP3. DP3 and WSClean are in the same commit as FLoCS.
It builds fine.
> Update to GCC 14

- container/Dockerfile-20250113
> Remove WSClean src and build files

- container/Dockerfile-20250113
> remove WSRT_Measures.ztar

- container/Dockerfile-20250113
> Remove subversion

- container/Dockerfile-20250113
> Update DP3 comment

- container/Dockerfile-20250113
Im sorry, I forgot to change it in the previous PR.
> Fix WSClean date

- container/Dockerfile
There is no `generic` switch for `MARCH`. Formally, `generic` can only be used for `MTUNE`.
The other option is to change `MARCH` to `MTUNE` and leave this value as `generic`.
> Change `generic` to `x86-64`

- pipelines/LOFAR_ddparallel.py
In general, it is not recommended to use f-strings without placeholders (https://docs.astral.sh/ruff/rules/f-string-missing-placeholders/).
> Simplify f-string without placeholders

- container/Dockerfile
Is this not an artifact of an older version? The d/l link looks fine.
> Simplify LTA installation

- container/Dockerfile-20250113
Make sure everything is compiled with proper optimizations. Especially casacore, where there is no `DTARGET_CPU` option.
> Add C flags

- container/Dockerfile
It is the component that takes the longest to build.
> Speedup CASAcore build

- pipelines/LOFAR_ddserial.py
- pipelines/LOFAR_extract.py
- pipelines/LOFAR_preprocess.py
- pipelines/LOFAR_quality.py
- scripts/breizorro.py
> Fix last unnecessary f-strings

- scripts/BLsmooth.py
Assign `in_bl` only if the condition `if std_t < 0.5` is false.
> Speedup BLsmooth

- container/Dockerfile
To follow this:
https://git.astron.nl/RD/DP3/-/commit/20720719f4392cae19ba4ee70dcd2898dde25cc5#c596c5e20c4ac53de196cd8f03addaa90507ebf6_49_48
It also avoids using FTP (FTP support was removed from wget 2).
> Update `WSRT_Measures` download

- README.md
Change `target_extraction` to `LOFAR_extract` and remove few trailing spaces.
> Update `README.md` extraction section
